version: "3.0"
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: main
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
